package com.rendezvous.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.rendezvous.common.JsonDateSerializer;

import java.util.Date;

/**
 * Data entity for dine_out_plan.
 *
 * @author Rupali Paunikar
 */
@DynamoDBTable(tableName = "dine_out_plan")
public class DineOutPlan {

    @JsonIgnore
    private String planId;
    private String userId;
    private String planName;
    private String dineOutType;
    private String venue;
    private String description;
    @JsonSerialize(using = JsonDateSerializer.class)
    private Date date;

    public DineOutPlan(){}

    public DineOutPlan(String planId, String userId, String planName, String dineOutType, String venue, String description, Date date) {
        this.planId = planId;
        this.userId = userId;
        this.planName = planName;
        this.dineOutType = dineOutType;
        this.venue = venue;
        this.description = description;
        this.date = date;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userIdIndex")
    public String getUserId() {
        return userId;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getPlanName() {
        return planName;
    }

    public void setPlanName(final String planName) {
        this.planName = planName;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getPlanId() {
        return planId;
    }

    public void setPlanId(final String planId) {
        this.planId = planId;
    }

    @DynamoDBAttribute
    public String getVenue() {
        return venue;
    }

    public void setVenue(final String venue) {
        this.venue = venue;
    }

    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    public void setDate(final Date date) {
        this.date = date;
    }

    @DynamoDBAttribute
    public String getDineOutType() {
        return dineOutType;
    }

    public void setDineOutType(final String dineOutType) {
        this.dineOutType = dineOutType;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "DineOutPlan{" +
                "planId='" + planId + '\'' +
                ", userId='" + userId + '\'' +
                ", planName='" + planName + '\'' +
                ", dineOutType='" + dineOutType + '\'' +
                ", venue='" + venue + '\'' +
                ", description='" + description + '\'' +
                ", date=" + date +
                '}';
    }
}
